services:
    app:
       build: .
       container_name: ciTrace_demo_API_container
       command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload 
       ports:
           - 8080:80
       volumes:
           - .:/app #Se viene cambiato qualcosa nel folder corrente verrà modificato anche nella folder "app"
           
    db:
       image: postgres:latest
       ports:
           - "5432:5432"
       environment:
           POSTGRES_DB: db_CiTrace_API
           POSTGRES_USER: username
           POSTGRES_PASSWORD: password
       volumes:
           - postgres_data:/var/lib/postgresql/data
                
volumes:
       postgres_data:
